<?php
$content = [
    'video'      => materialAsset('slider/A1/Advanced/chapter-8/video/appartment-encrypted/appartment.m3u8'),
    'thumbnail'  => materialAsset('slider/A1/Advanced/chapter-8/video/video-thumbnail.webp'),
    'isQuiz' => 1,
    'questions' => [
        [
            'time' => 16500,
            'type' => 'multiple_choice',
            'question' => 'Question 1: What kind of people live in the neighbourhood?',
            'options' => [
                'Only students',
                'Only families',
                'Older people, young families, and students',
                'Only workers',
            ],
            'correct_answer' => 2,
            'points' => 10,
        ],
        [
            'time' => 25500,
            'type' => 'multiple_choice',
            'question' => 'Question 2: How do they describe the neighbourhood?',
            'options' => [
                'Dangerous and crowded',
                'Safe and quiet',
                'Old and empty',
                'Noisy and busy',
            ],
            'correct_answer' => 1,
            'points' => 10,
        ],
        [
            'time' => 45500,
            'type' => 'multiple_choice',
            'question' => 'Question 3: How long does it take to get downtown?',
            'options' => [
                'One hour',
                'Thirty minutes',
                'Ten minutes',
                'A few minutes',
            ],
            'correct_answer' => 3,
            'points' => 10,
        ],
        [
            'time' => 61500,
            'type' => 'multiple_choice',
            'question' => 'Question 4: What do they say about restaurants?',
            'options' => [
                'There are no restaurants',
                'There are a few restaurants',
                'There are a lot of restaurants',
                'There is one restaurant',
            ],
            'correct_answer' => 2,
            'points' => 10,
        ],
    ],

    'subtitles'  => [
        ['start' => 0, 'end' => 2.5, 'text' => "We really like the apartment."],
        ['start' => 3.5, 'end' => 5, 'text' => "Yeah, it's good. Very roomy."],
        ['start' => 6, 'end' => 7, 'text' => "Good"],
        ['start' => 8, 'end' => 9, 'text' => "What's the neighbourhood like?"],
        ['start' => 10.5, 'end' => 16, 'text' => "It's a very special neighbourhood. There's a real mix of people here. There are older people, young families, and students."],
        ['start' => 16, 'end' => 19, 'text' => "There's a lot of different cultures."],
        ['start' => 19.5, 'end' => 21.5, 'text' => "So, It's a safe neighbourhood?"],
        ['start' => 22, 'end' => 25, 'text' => "Yes. Very safe. And quiet. Not much noise usually."],
        ['start' => 27, 'end' => 29, 'text' => "Is there much crime?"],
        ['start' => 29, 'end' => 35.5, 'text' => "Oh, no. There isn't much now. Well, there were some problems, but that was 10 years ago."],
        ['start' => 37, 'end' => 39.5, 'text' => "Okay. What about public transportation?"],
        ['start' => 41, 'end' => 45, 'text' => "The public transportation is excellent. It's just a few minutes to downtown."],
        ['start' => 46, 'end' => 50.5, 'text' => "We like to eat out. Are there many restaurants and coffee shops?"],
        ['start' => 51, 'end' => 61, 'text' => "Oh, yes. There are a lot of restaurants. Just take a walk down the street to the end and you'll see there are lots of Greek and Italian restaurants. There's Indian, Chinese, everything."],
        ['start' => 61, 'end' => 65.5, 'text' => "Sounds great. Okay, let's take a look. Thank you for your help."],
        ['start' => 66, 'end' => 70, 'text' => "It was my pleasure. Give me a call this afternoon because this apartment won't last long."],
        ['start' => 70, 'end' => 73, 'text' => "Okay, thank you. Bye-bye. Bye."],
        ['start' => 89, 'end' => 91, 'text' => "I love that bookstore. What a great neighbourhood."],
        ['start' => 91.8, 'end' => 92.3, 'text' => "Yeah."],
        ['start' => 92.7, 'end' => 95.5, 'text' => "there's a movie theater and restaurants."],
        ['start' => 95.5, 'end' => 96.5, 'text' => "Movie theater, Restaurants!"],
        ['start' => 97, 'end' => 100, 'text' => "There's a furniture store. And there's a jewelry store."],
        ['start' => 100.5, 'end' => 102.5, 'text' => "My birthday's coming up next month."],
        ['start' => 103, 'end' => 104, 'text' => "Yeah, I know."],
        ['start' => 105, 'end' => 107, 'text' => "Look, Luis, there's a really nice grocery store."],
        ['start' => 107, 'end' => 110, 'text' => "Yeah, it's a nice grocery store."],
        ['start' => 110.8, 'end' => 113, 'text' => "And there are a lot of really good coffee shops."],
        ['start' => 113, 'end' => 115, 'text' => "I really like this neighbourhood."],
        ['start' => 115, 'end' => 116, 'text' => "Yeah, it's really great."],
        ['start' => 122.5, 'end' => 124, 'text' => "Wow. That's an amazing guitar."],
        ['start' => 124, 'end' => 126.8, 'text' => "So, can we take the apartment?"],
        ['start' => 127, 'end' => 129, 'text' => "Sure, why not? Let's go for it."],

    ],
];
?>
@include("slider.video.interactive", ['content' => $content])