@php
    $content = [
        'page_title'    => 'Let’s practise!',
        'title'         => 'Let’s practise!',
        'subtitle'      => 'Drag and drop the words or phrases from the box.',
        'audio'         => materialAsset('slider/A1/Beginner/chapter-2/audios/slide9.mp3'),
        'script'        => [
            "Molly: Excuse me. Hello. My name is Molly. What's your name?",
            "Pete: I'm Pete. My friends call me Pete.",
            "Molly: My friends call me Molly. Hi, Pete. It's nice to meet you.",
            "Pete: It's nice to meet you, too.",
            "Molly: Are you a student here?",
            "Pete: Yes, I am. My class is at nine o'clock with Miss Taylor.",
            "Molly: Miss Taylor? She's my teacher. I'm in your class, too.",
            "Pete: Great! Where is our class?",
            "Pete: It's over there.",
            "Peter: Hi, I'm Peter. Peter Crump. I'm in your class.",
            "Teacher: Hi, Peter. Nice to meet you. Hello, what's your name?",
            "Molly: I'm Molly.",
            "Teacher: Hello, Holly. Is that H - o - l - l - y?",
            "Molly: No, it's Molly. M - o - l - l - y.",
            "Teacher: M - o - l - l - y hmm What's your last name Molly?",
            "Molly: Lin. L - I - N.",
            "Teacher: Peter Crump and Molly Lin.",
            "Peter: Oh! Wait. Excuse me. Are you Miss Taylor?",
            "Teacher: Oh. No, I'm not. I'm Mrs. Smith. Miss Taylor is in room 203. Over there.",
            "Peter: Oh! Thanks.",
            "Teacher: You are welcome, Peter.",
            "Peter: Goodbye.",
            "Teacher: Have a good day!",
            "Molly: Hello, Teacher.",
            "Miss Taylor: Yes.",
            "Molly: I'm Molly Lin.",
            "Miss Taylor: Hi, Molly. Nice to meet you. Oh, here you are. Welcome Molly.",
            "Molly: Thank you.",
            "Peter: Hi. I'm Peter. Peter Crump.",
            "Miss Taylor: You're Peter. Okay. Let's begin class.",
        ],


        'sentences' => [
            "<strong class='text-pink-600 dark:text-pink-400'>Molly:</strong> Excuse me. Hello. My name is Molly. {{1}}",
            "<strong class='text-blue-600 dark:text-blue-400'>Pete:</strong> I'm Pete. {{2}}",
            "<strong class='text-pink-600 dark:text-pink-400'>Molly:</strong> My friends call me Molly. Hi, Pete. {{3}}",
            "<strong class='text-blue-600 dark:text-blue-400'>Pete:</strong> {{4}}",
            "<strong class='text-pink-600 dark:text-pink-400'>Molly:</strong> Are you a student here?",
            "<strong class='text-blue-600 dark:text-blue-400'>Pete:</strong> {{5}} My class is at nine o'clock with Miss Taylor.",
            "<strong class='text-pink-600 dark:text-pink-400'>Molly:</strong> Miss Taylor? {{6}} my teacher. {{7}}.",
            "<strong class='text-blue-600 dark:text-blue-400'>Pete:</strong> Great! {{8}}",
            "<strong class='text-blue-600 dark:text-blue-400'>Pete:</strong> It's over there.",
            "<strong class='text-cyan-700 dark:text-cyan-300'>Peter:</strong> {{9}} Peter Crump. I'm in your class.",
            "<strong class='text-emerald-600 dark:text-emerald-400'>Teacher:</strong> Hi, Peter. Nice to meet you. Hello, what's your name?",
            "<strong class='text-pink-600 dark:text-pink-400'>Molly:</strong> I'm Molly.",
            "<strong class='text-emerald-600 dark:text-emerald-400'>Teacher:</strong> Hello, {{10}} Is that H - o - l - l - y?",
            "<strong class='text-pink-600 dark:text-pink-400'>Molly:</strong> No, {{11}} M - o - l - l - y.",
            "<strong class='text-emerald-600 dark:text-emerald-400'>Teacher:</strong> M - o - l - l - y hmm {{12}}",
            "<strong class='text-pink-600 dark:text-pink-400'>Molly:</strong> Lin. L - I - N.",
            "<strong class='text-emerald-600 dark:text-emerald-400'>Teacher:</strong> Peter Crump and Molly Lin.",
            "<strong class='text-cyan-700 dark:text-cyan-300'>Peter:</strong> Oh! Wait. {{13}} Are you Miss Taylor?",
            "<strong class='text-emerald-600 dark:text-emerald-400'>Teacher:</strong> Oh. {{14}} I'm Mrs. Smith. Miss Taylor is in room 203. Over there.",
            "<strong class='text-cyan-700 dark:text-cyan-300'>Peter:</strong> Oh! {{15}}",
            "<strong class='text-emerald-600 dark:text-emerald-400'>Teacher:</strong> {{16}}",
            "<strong class='text-cyan-700 dark:text-cyan-300'>Peter:</strong> Goodbye.",
            "<strong class='text-emerald-600 dark:text-emerald-400'>Teacher:</strong> {{17}}",
            "<strong class='text-pink-600 dark:text-pink-400'>Molly:</strong> Hello, Teacher.",
            "<strong class='text-violet-600 dark:text-violet-300'>Miss Taylor:</strong> Yes.",
            "<strong class='text-pink-600 dark:text-pink-400'>Molly:</strong> I'm Molly Lin.",
            "<strong class='text-violet-600 dark:text-violet-300'>Miss Taylor:</strong> Hi, Molly. Nice to meet you. {{18}} Welcome Molly.",
            "<strong class='text-pink-600 dark:text-pink-400'>Molly:</strong> {{19}}",
            "<strong class='text-cyan-700 dark:text-cyan-300'>Peter:</strong> Hi. I'm Peter. Peter Crump.",
            "<strong class='text-violet-600 dark:text-violet-300'>Miss Taylor:</strong> {{20}} Peter. Okay. Let's begin class.",
        ],

        'answers' => [
            "What's your name?",
            'My friends call me Pete.',
            "It's nice to meet you.",
            "It's nice to meet you, too.",
            'Yes, I am.',
            "She's",
            "I'm in your class, too.",
            'Where is our class?',
            "Hi, I'm Peter.",
            'Holly.',
            "it's Molly.",
            "What's your last name Molly?",
            'Excuse me.',
            "No, I'm not.",
            'Thanks.',
            'You are welcome, Peter.',
            'Have a good day!',
            'Oh, Here you are',
            'Thank you.',
            "You're",
        ],
    ];
@endphp

@include("slider.game.drag-and-drop-blanks")
