<?php
$content = [
    'video'     => materialAsset('slider/A1/Advanced/chapter-10/video/encrypted/slide-5.m3u8'),
    'thumbnail' => materialAsset('slider/A1/Advanced/chapter-10/img/slide-5.webp'),

    'isQuiz' => 1,
    'showCC' => true,
    'showTranscript' => true,

    'questions' => [
        [
            'time' => 15000,
            'type' => 'multiple_choice',
            'question' => 'What is Bully doing at the beginning of the video?',
            'options' => ['Eating breakfast', 'Exercising', 'Sleeping', 'Cooking'],
            'correct_answer' => 2,
            'points' => 10,
        ],
        [
            'time' => 24000,
            'type' => 'multiple_choice',
            'question' => 'What is Sean doing?',
            'options' => ['Reading a book', 'Studying Spanish', 'Eating breakfast', 'Going to work'],
            'correct_answer' => 1,
            'points' => 10,
        ],
        [
            'time' => 35000,
            'type' => 'multiple_choice',
            'question' => 'What is Tim doing?',
            'options' => ['Cooking', 'Snowboarding', 'Sleeping', 'Watching TV'],
            'correct_answer' => 1,
            'points' => 10,
        ],
        [
            'time' => 50000,
            'type' => 'multiple_choice',
            'question' => 'What is Georgie doing?',
            'options' => ['Listening to music', 'Studying Spanish', 'Playing video games', 'Exercising'],
            'correct_answer' => 1,
            'points' => 10,
        ],
        [
            'time' => 100000,
            'type' => 'multiple_choice',
            'question' => 'What is Bully doing now?',
            'options' => ['Watching TV', 'Reading a book', 'Playing video games', 'Sleeping'],
            'correct_answer' => 2,
            'points' => 10,
        ],
    ],

    'subtitles' => [
        ['start' => 0,   'end' => 12,  'text' => 'What are you doing?'],
        ['start' => 12,  'end' => 15,  'text' => 'Hello, Bully.'],
        ['start' => 15,  'end' => 18,  'text' => 'Hi, Tim. What are you doing?'],
        ['start' => 18,  'end' => 20,  'text' => "I'm exercising."],
        ['start' => 20,  'end' => 24,  'text' => 'Hi, Sean. Hi, Bully. What are you doing?'],
        ['start' => 24,  'end' => 26,  'text' => "I'm eating breakfast."],
        ['start' => 26,  'end' => 30,  'text' => 'Hi, Georgie. Hi, Sean. What are you doing?'],
        ['start' => 30,  'end' => 32,  'text' => "I'm going to work."],
        ['start' => 32,  'end' => 35,  'text' => 'What are you doing, Tim?'],
        ['start' => 35,  'end' => 39,  'text' => "I'm cooking."],
        ['start' => 39,  'end' => 42,  'text' => 'What are you doing now, Bully?'],
        ['start' => 42,  'end' => 45,  'text' => "Oh, I'm reading a book."],
        ['start' => 45,  'end' => 47,  'text' => 'What are you doing, Sean?'],
        ['start' => 47,  'end' => 49,  'text' => "I'm snowboarding."],
        ['start' => 49,  'end' => 50,  'text' => 'What are you doing, Georgie?'],
        ['start' => 50,  'end' => 53,  'text' => "I'm studying Spanish."],
        ['start' => 53,  'end' => 60,  'text' => 'What are you doing?'],
        ['start' => 60,  'end' => 63,  'text' => "I'm studying English."],
        ['start' => 63,  'end' => 72,  'text' => 'What are you doing now?'],
        ['start' => 72,  'end' => 75,  'text' => "I'm reading a book."],
        ['start' => 75,  'end' => 92,  'text' => 'Great.'],
        ['start' => 92,  'end' => 95,  'text' => 'What is Tim doing?'],
        ['start' => 95,  'end' => 97,  'text' => "He's watching TV."],
        ['start' => 97,  'end' => 100, 'text' => 'What is Bully doing?'],
        ['start' => 100, 'end' => 103, 'text' => "He's playing video games."],
        ['start' => 103, 'end' => 109, 'text' => 'What is Georgie doing?'],
        ['start' => 109, 'end' => 113, 'text' => "She's sleeping."],
        ['start' => 113, 'end' => 116, 'text' => "What's Sean doing?"],
        ['start' => 116, 'end' => 119, 'text' => "She's listening to music."],
        ['start' => 119, 'end' => 126, 'text' => 'What are you doing?'],
        ['start' => 126, 'end' => 128, 'text' => "I'm watching TV."],
        ['start' => 128, 'end' => 135, 'text' => "What's Tim doing?"],
        ['start' => 135, 'end' => 137, 'text' => "He's cooking."],
        ['start' => 137, 'end' => 142, 'text' => 'Well done.'],
        ['start' => 142, 'end' => 145, 'text' => 'What is Georgie doing?'],
        ['start' => 145, 'end' => 148, 'text' => "She's eating lunch."],
        ['start' => 148, 'end' => 149, 'text' => "That's right."],
        ['start' => 149, 'end' => 155, 'text' => 'What is Tim doing now?'],
    ],
];
?>

@include("slider.video.interactive", ['content' => $content])
