@php
    $content = [
        'title'    => 'New Vocabulary',
        'subtitle' => '',

        'groups' => [
            [
                'title' => '',
                'grid_class' => 'grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 xl:grid-cols-5',
                'items' => [
                    [
                        'text'     => 'kneel (verb)',
                        'subtitle' => 'to go down onto one or both knees.',
                        'example'  => 'The detective knelt to examine the footprints.',
                        'emoji'    => '🧎',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-1/audios/slide7/kneel.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-1/img/slide7/kneel.webp'),
                    ],
                    [
                        'text'     => 'muddy (adjective)',
                        'subtitle' => 'covered with or full of mud.',
                        'example'  => 'The boy\'s shoes were muddy after the storm.',
                        'emoji'    => '🟤',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-1/audios/slide7/muddy.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-1/img/slide7/muddy.webp'),
                    ],
                    [
                        'text'     => 'footprint (noun)',
                        'subtitle' => 'the mark left by a foot or shoe.',
                        'example'  => 'The police found muddy footprints near the door.',
                        'emoji'    => '👣',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-1/audios/slide7/footprint.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-1/img/slide7/footprint.webp'),
                    ],
                    [
                        'text'     => 'latch (noun)',
                        'subtitle' => 'a small device used to keep a door or gate closed.',
                        'example'  => 'The window latch was broken.',
                        'emoji'    => '🚪',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-1/audios/slide7/latch.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-1/img/slide7/latch.webp'),
                    ],
                    [
                        'text'     => 'fasten (verb)',
                        'subtitle' => 'to close or secure something firmly.',
                        'example'  => 'She fastened the gate before leaving.',
                        'emoji'    => '🔒',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-1/audios/slide7/fasten.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-1/img/slide7/fasten.webp'),
                    ],
                    [
                        'text'     => 'force (verb)',
                        'subtitle' => 'to make something open or move by using strength.',
                        'example'  => 'Someone forced the door open.',
                        'emoji'    => '💪',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-1/audios/slide7/force.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-1/img/slide7/force.webp'),
                    ],
                    [
                        'text'     => 'intruder (noun)',
                        'subtitle' => 'a person who enters a place without permission.',
                        'example'  => 'The family thought the intruder had entered the house.',
                        'emoji'    => '🕵️',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-1/audios/slide7/intruder.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-1/img/slide7/intruder.webp'),
                    ],
                    [
                        'text'     => 'scratch (noun)',
                        'subtitle' => 'a small cut or mark on a surface or skin.',
                        'example'  => 'There were scratches on the wooden floor.',
                        'emoji'    => '〰️',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-1/audios/slide7/scratch.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-1/img/slide7/scratch.webp'),
                    ],
                    [
                        'text'     => 'shadow (noun)',
                        'subtitle' => 'a dark shape made when light is blocked.',
                        'example'  => 'They saw a shadow outside the window.',
                        'emoji'    => '👤',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-1/audios/slide7/shadow.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-1/img/slide7/shadow.webp'),
                    ],
                    [
                        'text'     => 'whisper (verb)',
                        'subtitle' => 'to speak very quietly.',
                        'example'  => 'The children whispered because they were scared.',
                        'emoji'    => '🤫',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-1/audios/slide7/whisper.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-1/img/slide7/whisper.webp'),
                    ],
                    [
                        'text'     => 'storm (noun)',
                        'subtitle' => 'a period of very bad weather with strong wind and rain.',
                        'example'  => 'The storm started during the night.',
                        'emoji'    => '⛈️',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-1/audios/slide7/storm.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-1/img/slide7/storm.webp'),
                    ],
                    [
                        'text'     => 'realize (verb)',
                        'subtitle' => 'to suddenly understand something.',
                        'example'  => 'She realized the door was unlocked.',
                        'emoji'    => '💡',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-1/audios/slide7/realize.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-1/img/slide7/realize.webp'),
                    ],
                    [
                        'text'     => 'freeze (froze) (verb)',
                        'subtitle' => 'to stop moving because of fear or surprise.',
                        'example'  => 'He froze when he heard a strange noise.',
                        'emoji'    => '😨',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-1/audios/slide7/freeze-froze.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-1/img/slide7/freeze-froze.webp'),
                    ],
                    [
                        'text'     => 'clue (noun)',
                        'subtitle' => 'a piece of information that helps solve a mystery.',
                        'example'  => 'The muddy footprints were an important clue.',
                        'emoji'    => '🔍',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-1/audios/slide7/clue.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-1/img/slide7/clue.webp'),
                    ],
                    [
                        'text'     => 'evidence (noun)',
                        'subtitle' => 'facts or objects that help prove what happened.',
                        'example'  => 'The detective looked for evidence in the room.',
                        'emoji'    => '📦',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-1/audios/slide7/evidence.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-1/img/slide7/evidence.webp'),
                    ],
                ],
            ],
        ],
    ];
@endphp

@include('slider.vocab.image-card', ['content' => $content])