<?php
$content = [
    'title'          => "Let's Watch This Video",
    'video'          => materialAsset('slider/A2/Beginner/chapter-4/video/what-did-you-do-yesterday-encrypted/what-did-you-do-yesterday.m3u8'),
    'thumbnail'      => materialAsset('slider/A2/Beginner/chapter-4/img/slide5.webp'),
    'isQuiz'         => 0,
    'showTranscript' => 0,

    'questions' => [
        [
            'time' => 11000,
            'type' => 'multiple_choice',
            'question' => '1- What did Pete buy?',
            'options' => ['Food', 'New clothes', 'Shoes', 'A book'],
            'correct_answer' => 1,
            'points' => 10,
        ],
        [
            'time' => 20500,
            'type' => 'multiple_choice',
            'question' => '2- Who did Pete play tennis with?',
            'options' => ['John', 'His sister', 'Tom', 'Alone'],
            'correct_answer' => 2,
            'points' => 10,
        ],
        [
            'time' => 38600,
            'type' => 'multiple_choice',
            'question' => '4- Ahmed went to the park alone.',
            'options' => ['True', 'False'],
            'correct_answer' => 1,
            'points' => 10,
        ],
        [
            'time' => 45200,
            'type' => 'multiple_choice',
            'question' => '3- What flavour of ice cream did Ahmed have?',
            'options' => ['Vanilla', 'Strawberry', 'Chocolate', 'Mango'],
            'correct_answer' => 2,
            'points' => 10,
        ],
        [
            'time' => 57500,
            'type' => 'multiple_choice',
            'question' => '5- The movie was about space travel.',
            'options' => ['True', 'False'],
            'correct_answer' => 0,
            'points' => 10,
        ],
    ],

    'subtitles' => [
        ['start' => 0,  'end' => 2,  'text' => 'Anna: What did you do yesterday?'],
        ['start' => 2,  'end' => 5.5,  'text' => 'Pete: I did many things. I went shopping.'],
        ['start' => 7,  'end' => 9,  'text' => 'Anna: What did you buy?'],
        ['start' => 9,  'end' => 10.5,  'text' => 'Pete: I bought new clothes.'],
        ['start' => 11.7,  'end' => 13.5,  'text' => 'Anna: What else did you do?'],
        ['start' => 13.7,  'end' => 16,  'text' => 'Pete: I also played tennis.'],
        ['start' => 16.7,  'end' => 18.5,  'text' => 'Anna: Who did you play with?'],
        ['start' => 18.7,  'end' => 20,  'text' => 'Pete: I played with Tom.'],
        ['start' => 21,  'end' => 22,  'text' => 'Anna: Did you win?'],
        ['start' => 22.7,  'end' => 24,  'text' => 'Pete: Yes, I won!'],
        ['start' => 27,  'end' => 29,  'text' => 'Suzy: What did you do yesterday?'],
        ['start' => 29,  'end' => 32,  'text' => 'Ahmed: I went to the park. It was a sunny day.'],
        ['start' => 32.5,  'end' => 35,  'text' => 'Suzy: That sounds nice. Did you go alone?'],
        ['start' => 35.5,  'end' => 38.5,  'text' => 'Ahmed: No, I went there with John. We had ice cream.'],
        ['start' => 38.7,  'end' => 41.7,  'text' => 'Suzy: Ice cream is my favorite. Which flavor did you have?'],
        ['start' => 41.7,  'end' => 45,  'text' => 'Ahmed: I had chocolate. John had vanilla. Yummy!'],
        ['start' => 45.5,  'end' => 47,  'text' => 'Suzy: Yummy!'],
        ['start' => 47.7,  'end' => 50, 'text' => 'Rana: Did you watch the movie last night?'],
        ['start' => 50, 'end' => 52.5, 'text' => 'Mohamed: Yes, I did. It was amazing!'],
        ['start' => 52.7, 'end' => 54.5, 'text' => 'Rana: Really? What was it about?'],
        ['start' => 54.7, 'end' => 57, 'text' => 'Mohamed: It was a movie about space travel.'],
        ['start' => 58, 'end' => 61.5, 'text' => 'Rana: That sounds interesting. Who did you watch it with?'],
        ['start' => 61.7, 'end' => 65, 'text' => 'Mohamed: I watched it with my sister. She loved it.'],
    ],
];
?>

@include("slider.video.interactive", ['content' => $content])