<?php
$content=[
    'video'=>materialAsset('slider/A1/Beginner/chapter-4/video/encrypted/slide4.m3u8'),
    'thumbnail'=>materialAsset('slider/A1/Beginner/chapter-4/video/my-family.webp'),
    'isQuiz'=>1,
    'questions'=>[
        [
            'time' => 10000,
            'type' => 'multiple_choice',
            'question' => 'A family tree is…',
            'options' => [
                'A picture of animals',
                'A diagram showing family members and their relations',
                'A list of friends',
                'A map of a city',
            ],
            'correct_answer' => 1,
            'points' => 10,
        ],
        [
            'time' => 19000,
            'type' => 'multiple_choice',
            'question' => 'Who is the sister of my father?',
            'options' => [
                'My aunt',
                'My cousin',
                'My grandmother',
                'My mother',
            ],
            'correct_answer' => 0,
            'points' => 10,
        ],
        [
            'time' => 34500,
            'type' => 'multiple_choice',
            'question' => 'My mother and my father are…',
            'options' => [
                'My grandparents',
                'My parents',
                'My siblings',
                'My cousins',
            ],
            'correct_answer' => 1,
            'points' => 10,
        ],
        [
            'time' => 50000,
            'type' => 'multiple_choice',
            'question' => 'My aunt and her husband have two sons. Who are they?',
            'options' => [
                'My brothers',
                'My cousins',
                'My uncles',
                'My parents',
            ],
            'correct_answer' => 1,
            'points' => 10,
        ],
        [
            'time' => 53000,
            'type' => 'multiple_choice',
            'question' => 'My mother’s brother is…',
            'options' => [
                'My cousin',
                'My uncle',
                'My grandfather',
                'My father',
            ],
            'correct_answer' => 1,
            'points' => 10,
        ],
    ],
    'subtitles' => [
        ['start' => 1,  'end' => 3, 'text' => "The family tree."],
        ['start' => 3, 'end' => 5, 'text' => "A family tree is a diagram representing"],
        ['start' => 5, 'end' => 10, 'text' => "family members and how they are related."],
        ['start' => 10, 'end' => 13, 'text' => "These are my grandmother and my grandfather."],
        ['start' => 13, 'end' => 17, 'text' => "They have two children: my father and his sister."],
        ['start' => 17, 'end' => 19, 'text' => "That's my aunt."],
        ['start' => 19, 'end' => 24, 'text' => "These are also my grandparents. They are the parents of my mother. They have two children:"],
        ['start' => 24, 'end' => 27, 'text' => "my mother and her brother — that's my uncle."],
        ['start' => 27, 'end' => 30, 'text' => "My mother and my father are my parents."],
        ['start' => 30, 'end' => 36, 'text' => "They have three children: my sister, my brother, and me. We are siblings."],
        ['start' => 36, 'end' => 38, 'text' => "This is my aunt and her husband."],
        ['start' => 38, 'end' => 41, 'text' => "They have two sons. They are my cousins."],
        ['start' => 41, 'end' => 50, 'text' => "My mother's brother is my uncle. This is my second aunt, his wife. They have a daughter; she is also my cousin."],
        ['start' => 50, 'end' => 53, 'text' => "This is my family tree."],
    ],
];
?>
@include("slider.video.interactive",['content'=>$content])
