@php
    $content = [
        'title'    => 'New Vocabulary',
        'subtitle' => '',

        'groups' => [
            [
                'key'        => 'with-images',
                'grid_class' => 'grid-cols-2 sm:grid-cols-4 lg:grid-cols-4 xl:grid-cols-6',
                'items' => [
                    [
                        'text'     => 'trim (v.)',
                        'subtitle' => 'to cut a small amount to make something neat.',
                        'example'  => 'He trims his own beard.',
                        'emoji'    => '',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-7/audios/slide6/trim.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-7/img/slide6/trim.webp'),
                    ],
                    [
                        'text'     => 'apartment (n.)',
                        'subtitle' => 'a flat or a set of rooms for living in a building.',
                        'example'  => 'He painted his apartment.',
                        'emoji'    => '',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-7/audios/slide6/apartment.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-7/img/slide6/apartment.webp'),
                    ],
                    [
                        'text'     => 'repaint (v.)',
                        'subtitle' => 'to paint something again.',
                        'example'  => 'He got his mansion repainted pink.',
                        'emoji'    => '',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-7/audios/slide6/repaint.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-7/img/slide6/repaint.webp'),
                    ],
                    [
                        'text'     => 'mansion (n.)',
                        'subtitle' => 'a very large and expensive house.',
                        'example'  => 'Neerajito got one of his mansions repainted.',
                        'emoji'    => '',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-7/audios/slide6/mansion.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-7/img/slide6/mansion.webp'),
                    ],
                    [
                        'text'     => 'tailor (n.)',
                        'subtitle' => 'a person who makes or repairs clothes.',
                        'example'  => 'He gets his clothes made by his tailor.',
                        'emoji'    => '',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-7/audios/slide6/tailor.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-7/img/slide6/tailor.webp'),
                    ],
                    [
                        'text'     => 'limousine (n.)',
                        'subtitle' => 'a long, expensive car.',
                        'example'  => 'He gets driven all over the city in his limousine.',
                        'emoji'    => '',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-7/audios/slide6/limousine.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-7/img/slide6/limousine.webp'),
                    ],
                    [
                        'text'     => 'butler (n.)',
                        'subtitle' => 'a male servant who works in a rich person’s house.',
                        'example'  => 'His umbrella is held by his butler.',
                        'emoji'    => '',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-7/audios/slide6/butler.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-7/img/slide6/butler.webp'),
                    ],
                    [
                        'text'     => 'chef (n.)',
                        'subtitle' => 'a person whose job is to cook.',
                        'example'  => 'He has all of his meals cooked for him by his chef.',
                        'emoji'    => '',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-7/audios/slide6/chef.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-7/img/slide6/chef.webp'),
                    ],
                    [
                        'text'     => 'barber (n.)',
                        'subtitle' => 'a person who cuts men’s hair and grooms beards.',
                        'example'  => 'He has his beard trimmed by his personal barber.',
                        'emoji'    => '',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-7/audios/slide6/barber.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-7/img/slide6/barber.webp'),
                    ],
                    [
                        'text'     => 'driver (n.)',
                        'subtitle' => 'a person whose job is to drive a car.',
                        'example'  => 'He gets driven around the city by his driver.',
                        'emoji'    => '',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-7/audios/slide6/driver.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-7/img/slide6/driver.webp'),
                    ],
                    [
                        'text'     => 'umbrella (n.)',
                        'subtitle' => 'a device used to protect you from rain.',
                        'example'  => 'He has his umbrella held for him when it rains.',
                        'emoji'    => '',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-7/audios/slide6/umbrella.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-7/img/slide6/umbrella.webp'),
                    ],
                    [
                        'text'     => 'reggaeton (n.)',
                        'subtitle' => 'a popular style of music from Latin America.',
                        'example'  => 'Neerajito is a reggaeton artist.',
                        'emoji'    => '',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-7/audios/slide6/reggaeton.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-7/img/slide6/reggaeton.webp'),
                    ],
                ],
            ],

            [
                'key'        => '',
                'grid_class' => 'grid-cols-2 sm:grid-cols-4 lg:grid-cols-4',
                'items' => [
                    [
                        'text'     => 'regular (adj.)',
                        'subtitle' => 'normal; not special or unusual.',
                        'example'  => 'Neeraj is just a regular person.',
                        'emoji'    => '🙂',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-7/audios/slide6/regular.mp3'),
                    ],
                    [
                        'text'     => 'meal (n.)',
                        'subtitle' => 'food that you eat at one time.',
                        'example'  => 'He cooks his own meals.',
                        'emoji'    => '🍽️',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-7/audios/slide6/meal.mp3'),
                    ],
                    [
                        'text'     => 'lifestyle (n.)',
                        'subtitle' => 'the way a person lives.',
                        'example'  => 'Our friends have very different lifestyles.',
                        'emoji'    => '🏡',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-7/audios/slide6/lifestyle.mp3'),
                    ],
                    [
                        'text'     => 'wealthy (adj.)',
                        'subtitle' => 'having a lot of money.',
                        'example'  => 'Neerajito is a fabulously wealthy artist.',
                        'emoji'    => '💰',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-7/audios/slide6/wealthy.mp3'),
                    ],
                    [
                        'text'     => 'fabulously (adv.)',
                        'subtitle' => 'in a very impressive or extremely good way.',
                        'example'  => 'He is a fabulously wealthy reggaeton artist.',
                        'emoji'    => '✨',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-7/audios/slide6/fabulously.mp3'),
                    ],
                    [
                        'text'     => 'world-famous (adj.)',
                        'subtitle' => 'known by people all over the world.',
                        'example'  => 'Neerajito is a world-famous reggaeton artist.',
                        'emoji'    => '🌍',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-7/audios/slide6/world-famous.mp3'),
                    ],
                    [
                        'text'     => 'convenient (adj.)',
                        'subtitle' => 'suitable or helpful for your needs.',
                        'example'  => 'Getting things done for us is more convenient.',
                        'emoji'    => '👍',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-7/audios/slide6/convenient.mp3'),
                    ],
                    [
                        'text'     => 'cause (v.)',
                        'subtitle' => 'to make something happen.',
                        'example'  => 'You cause something to happen when you use the causative.',
                        'emoji'    => '➡️',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-7/audios/slide6/cause.mp3'),
                    ],
                ],
            ],
        ],
    ];
@endphp

@include('slider.vocab.image-card', ['content' => $content])