<?php
$content = [
    'page_title' => 'Watch Again & Do the Quiz',
    'title' => 'Watch Again & Do the Quiz',
    'subtitle' => '',

    'video' => materialAsset('slider/A1/Advanced/chapter-12/video/buy-phone-encrypted/buy-phone.m3u8'),
    'thumbnail' => materialAsset('slider/A1/Advanced/chapter-12/img/slide8.webp'),

    'isQuiz' => 1,
    'questions' => [
        [
            'time' => 15200,
            'type' => 'multiple_choice',
            'question' => '1. Why does the customer need a new phone?',
            'options' => [
                'It is lost',
                'It is broken',
                'It is new',
                'It is cheap',
            ],
            'correct_answer' => 1,
            'points' => 10,
        ],
        [
            'time' => 63800,
            'type' => 'multiple_choice',
            'question' => '2. Which phone is more expensive?',
            'options' => [
                'The smaller phone',
                'The bigger phone',
                'The pink phone',
                'The light phone',
            ],
            'correct_answer' => 1,
            'points' => 10,
        ],
        [
            'time' => 102000,
            'type' => 'multiple_choice',
            'question' => '3. Why does the customer buy the strong case?',
            'options' => [
                'It is cheap',
                'It is small',
                'She drops her phone a lot',
                'It is pink',
            ],
            'correct_answer' => 2,
            'points' => 10,
        ],
        [
            'time' => 110500,
            'type' => 'input',
            'question' => '4. What color phone does the customer choose?',
            'accepted_answers' => ['pink', 'the pink phone'],
            'points' => 10,
        ],
        [
            'time' => 117250,
            'type' => 'input',
            'question' => '5. What help does the assistant offer?',
            'accepted_answers' => [
                'to transfer data',
                'transfer data',
                'help transfer data',
                'he offers to transfer the data',
            ],
            'points' => 10,
        ],
    ],

    'subtitles'  => [
        ['start' => 0,   'end' => 2.5,   'text' => 'Assistant: Hi, welcome to Tech World Mobile. How can I help you today?'],
        ['start' => 3.5,   'end' => 7.5,  'text' => "Customer: Hi, I'm looking to buy a new phone. My old one stopped working yesterday."],
        ['start' => 8,  'end' => 10,  'text' => 'Assistant: Oh no, what happened to it?'],
        ['start' => 10,  'end' => 15,  'text' => 'Customer: It keeps turning off and the battery dies in 5 minutes. It\'s basically saying, "Please let me retire."'],
        ['start' => 15.5,  'end' => 20,  'text' => 'Assistant: Sounds like it\'s done. Do you have any brand in mind? Samsung, iPhone, Google.'],
        ['start' => 20.5,  'end' => 23.5,  'text' => "Customer: I'm not sure. I just want something easy to use with a good camera."],
        ['start' => 26.5,  'end' => 33,  'text' => 'Assistant: Great. In that case, I recommend this model here. It has a really good camera and a strong battery life.'],
        ['start' => 34,  'end' => 36,  'text' => "Customer: Oh, it looks nice. What's the price?"],
        ['start' => 36.8,  'end' => 41,  'text' => 'Assistant: This one is $699, but we also have a smaller version for $599.'],
        ['start' => 41.5,  'end' => 43,  'text' => "Customer: Hmm, what's the difference?"],
        ['start' => 45.5,  'end' => 51,  'text' => 'Assistant: The more expensive one has a bigger screen and a better camera at night. The cheaper one is lighter and easier to hold.'],
        ['start' => 51,  'end' => 53,  'text' => 'Customer: I like a lighter phone. Can I hold it?'],
        ['start' => 53,  'end' => 54,  'text' => 'Assistant: Of course.'],
        ['start' => 54,  'end' => 58,  'text' => 'Customer: Wow, it feels good in my hand. Does it have good storage?'],
        ['start' => 58,  'end' => 63,  'text' => 'Assistant: Yes, this one has 128 GB and you can also get a 256 GB version.'],
        ['start' => 64.8,  'end' => 67, 'text' => 'Customer: 128 GB is enough for me.'],
        ['start' => 69,  'end' => 71, 'text' => 'Customer: Does it come in different colors?'],
        ['start' => 71.5, 'end' => 74, 'text' => 'Assistant: Yes, black, white, blue, and pink.'],
        ['start' => 75, 'end' => 79, 'text' => 'Customer: Pink. I love pink. What about the warranty?'],
        ['start' => 79.8, 'end' => 83, 'text' => 'Assistant: You get one year included. If you want, you can add a 2-year protection plan for $79.'],
        ['start' => 85, 'end' => 87, 'text' => "Customer: Hmm, I think I'll take the one-year warranty for now."],
        ['start' => 87, 'end' => 90, 'text' => 'Assistant: No problem. Would you like a phone case or a screen protector?'],
        ['start' => 90.6, 'end' => 93, 'text' => 'Customer: Yes, a case, please. Something simple.'],
        ['start' => 94.8, 'end' => 99, 'text' => 'Assistant: Here are our bestselling cases. This one is $15. And this stronger one is $25.'],
        ['start' => 99, 'end' => 101.5, 'text' => "Customer: I'll take the $25 one. I drop my phone a lot."],
        ['start' => 104.5, 'end' => 107, 'text' => 'Assistant: Good choice. That one is very strong.'],
        ['start' => 107, 'end' => 110, 'text' => "Customer: Okay, I'll take the pink phone, 128 GB, and the case."],
        ['start' => 111.7, 'end' => 117, 'text' => 'Assistant: Perfect. I\'ll ring it up for you. Do you want me to help transfer your data?'],
        ['start' => 117.8, 'end' => 121, 'text' => "Customer: Yes, please. I'm terrible with technology."],
        ['start' => 121.7, 'end' => 124, 'text' => "Assistant: Don't worry. I'll take care of everything."],
        ['start' => 124.5, 'end' => 126, 'text' => "Customer: Thank you. You're very helpful."],
        ['start' => 127, 'end' => 130, 'text' => 'Assistant: My pleasure. Enjoy your new phone.'],
        ['start' => 130.7, 'end' => 133, 'text' => 'Customer: I will. Thank you so much.'],
    ],
];
?>

@include('slider.video.interactive', ['content' => $content])