<?php
$content = [
    'page_title' => 'Watch Again & Do the Quiz',
    'title' => 'Watch Again & Do the Quiz',
    'subtitle' => '',

    'video' => materialAsset('slider/A1/Beginner/chapter-2/video/encrypted/slide5.m3u8'),
    'thumbnail' => materialAsset('slider/A1/Beginner/chapter-2/video/slide5.webp'),

    'isQuiz' => 1,
    'questions' => [
        [
            'time' => 46000,
            'type' => 'multiple_choice',
            'question' => '1. Why does the customer need a new phone?',
            'options' => [
                'It is lost',
                'It is broken',
                'It is new',
                'It is cheap',
            ],
            'correct_answer' => 1,
            'points' => 10,
        ],
        [
            'time' => 66000,
            'type' => 'multiple_choice',
            'question' => '2. Which phone is more expensive?',
            'options' => [
                'The smaller phone',
                'The bigger phone',
                'The pink phone',
                'The light phone',
            ],
            'correct_answer' => 1,
            'points' => 10,
        ],
        [
            'time' => 96000,
            'type' => 'multiple_choice',
            'question' => '3. Why does the customer buy the strong case?',
            'options' => [
                'It is cheap',
                'It is small',
                'She drops her phone a lot',
                'It is pink',
            ],
            'correct_answer' => 2,
            'points' => 10,
        ],
        [
            'time' => 96000,
            'type' => 'input',
            'question' => '4. What color phone does the customer choose?',
            'accepted_answers' => ['pink', 'the pink phone'],
            'points' => 10,
        ],
        [
            'time' => 96000,
            'type' => 'input',
            'question' => '5. What help does the assistant offer?',
            'accepted_answers' => [
                'to transfer data',
                'transfer data',
                'help transfer data',
                'he offers to transfer the data',
            ],
            'points' => 10,
        ],
    ],

    'subtitles'  => [
        ['start' => 0,   'end' => 4,   'text' => 'Assistant: Hi, welcome to Tech World Mobile. How can I help you today?'],
        ['start' => 4,   'end' => 10,  'text' => "Customer: Hi, I'm looking to buy a new phone. My old one stopped working yesterday."],
        ['start' => 10,  'end' => 15,  'text' => 'Assistant: Oh no, what happened to it?'],
        ['start' => 15,  'end' => 30,  'text' => 'Customer: It keeps turning off and the battery dies in 5 minutes. It\'s basically saying, "Please let me retire." [laughter]'],
        ['start' => 30,  'end' => 37,  'text' => 'Assistant: Sounds like it\'s done. Do you have any brand in mind? Samsung, iPhone, Google.'],
        ['start' => 37,  'end' => 44,  'text' => "Customer: I'm not sure. I just want something easy to use with a good camera."],
        ['start' => 44,  'end' => 54,  'text' => 'Assistant: Great. In that case, I recommend this model here. It has a really good camera and a strong battery life.'],
        ['start' => 54,  'end' => 57,  'text' => "Customer: Oh, it looks nice. What's the price?"],
        ['start' => 57,  'end' => 63,  'text' => 'Assistant: This one is $699, but we also have a smaller version for $599.'],
        ['start' => 63,  'end' => 67,  'text' => "Customer: Hmm, what's the difference?"],
        ['start' => 67,  'end' => 76,  'text' => 'Assistant: The more expensive one has a bigger screen and a better camera at night. The cheaper one is lighter and easier to hold.'],
        ['start' => 76,  'end' => 79,  'text' => 'Customer: I like a lighter phone. Can I hold it?'],
        ['start' => 79,  'end' => 80,  'text' => 'Assistant: Of course. Here you go.'],
        ['start' => 80,  'end' => 89,  'text' => 'Customer: Wow, it feels good in my hand. Does it have good storage?'],
        ['start' => 89,  'end' => 94,  'text' => 'Assistant: Yes, this one has 128 GB and you can also get a 256 GB version.'],
        ['start' => 94,  'end' => 103, 'text' => 'Customer: 128 GB is enough for me. Does it come in different colors?'],
        ['start' => 103, 'end' => 104, 'text' => 'Assistant: Yes, black, white, blue, and pink.'],
        ['start' => 104, 'end' => 109, 'text' => 'Customer: Pink. I love pink. What about the warranty?'],
        ['start' => 109, 'end' => 116, 'text' => 'Assistant: You get one year included. If you want, you can add a 2-year protection plan for $79.'],
        ['start' => 116, 'end' => 122, 'text' => "Customer: Hmm, I think I'll take the one-year warranty for now."],
        ['start' => 122, 'end' => 129, 'text' => 'Assistant: No problem. Would you like a phone case or a screen protector?'],
        ['start' => 129, 'end' => 134, 'text' => 'Customer: Yes, a case, please. Something simple.'],
        ['start' => 134, 'end' => 138, 'text' => 'Assistant: Here are our bestselling cases. This one is $15. And this stronger one is $25.'],
        ['start' => 138, 'end' => 146, 'text' => "Customer: I'll take the $25 one. I drop my phone a lot. [laughter]"],
        ['start' => 146, 'end' => 148, 'text' => 'Assistant: Good choice. That one is very strong.'],
        ['start' => 148, 'end' => 154, 'text' => "Customer: Okay, I'll take the pink phone, 128 GB, and the case."],
        ['start' => 154, 'end' => 157, 'text' => 'Assistant: Perfect. I\'ll ring it up for you. Do you want me to help transfer your data?'],
        ['start' => 157, 'end' => 160, 'text' => "Customer: Yes, please. I'm terrible with technology."],
        ['start' => 160, 'end' => 166, 'text' => "Assistant: Don't worry. I'll take care of everything."],
        ['start' => 166, 'end' => 171, 'text' => "Customer: Thank you. You're very helpful."],
        ['start' => 171, 'end' => 171.5, 'text' => 'Assistant: My pleasure. Enjoy your new phone.'],
        ['start' => 171.5, 'end' => 175, 'text' => 'Customer: I will. Thank you so much.'],
    ],
];
?>

@include('slider.video.interactive', ['content' => $content])
