<?php
$content = [
    'page_title' => '',
    'title' => 'Let’s watch this video',
    'subtitle' => "What does he / she look like?",

    'video' => materialAsset('slider/A1/Beginner/chapter-7/video/encrypted/conversation.m3u8'),
    'thumbnail' => materialAsset(''),

    'maxPlaybackSeconds' => 217,

    'isQuiz' => 0,
    'questions' => [],

    'subtitles' => [
        ['start' => 0, 'end' => 3, 'text' => 'A2 Unit 3: Appearances'],
        ['start' => 3, 'end' => 7, 'text' => 'What does he or she look like?'],
        ['start' => 7, 'end' => 10, 'text' => "Bully: It's my birthday today."],
        ['start' => 10, 'end' => 13, 'text' => 'Friend: Happy birthday, Bully.'],
        ['start' => 13, 'end' => 15, 'text' => 'Bully: Thank you.'],
        ['start' => 15, 'end' => 19, 'text' => 'Friend: But Bully, do you have a birthday cake?'],
        ['start' => 19, 'end' => 23, 'text' => "Bully: Yes, it's right here. Where's my birthday cake?"],
        ['start' => 23, 'end' => 27, 'text' => 'Friend: I saw someone with your cake.'],
        ['start' => 27, 'end' => 30, 'text' => 'Bully: Was it a man or a woman?'],
        ['start' => 30, 'end' => 32, 'text' => 'Friend: It was a man.'],
        ['start' => 32, 'end' => 36, 'text' => 'Bully: A man? What did he look like?'],
        ['start' => 36, 'end' => 39, 'text' => 'Friend: He had short hair.'],
        ['start' => 39, 'end' => 43, 'text' => 'Bully: Okay. What color hair did he have?'],
        ['start' => 43, 'end' => 46, 'text' => 'Friend: He had blonde hair.'],
        ['start' => 46, 'end' => 51, 'text' => 'Bully: Did he have curly hair or straight hair?'],
        ['start' => 51, 'end' => 54, 'text' => 'Friend: He had curly hair.'],
        ['start' => 54, 'end' => 58, 'text' => 'Bully: What color eyes did he have?'],
        ['start' => 58, 'end' => 61, 'text' => 'Friend: He had brown eyes.'],
        ['start' => 61, 'end' => 65, 'text' => 'Bully: Was he tall or short?'],
        ['start' => 65, 'end' => 68, 'text' => 'Friend: He was tall.'],
        ['start' => 68, 'end' => 71, 'text' => 'Bully: Is this him?'],
        ['start' => 71, 'end' => 74, 'text' => "Friend: Yes, that's him."],
        ['start' => 74, 'end' => 79, 'text' => 'Bully: I saw someone with a cake, too. Was it a man or a woman?'],
        ['start' => 79, 'end' => 82, 'text' => 'Friend: It was a woman.'],
        ['start' => 82, 'end' => 86, 'text' => 'Bully: What did she look like?'],
        ['start' => 86, 'end' => 89, 'text' => 'Friend: She had long hair.'],
        ['start' => 89, 'end' => 93, 'text' => 'Bully: What color hair did she have?'],
        ['start' => 93, 'end' => 96, 'text' => 'Friend: She had brown hair.'],
        ['start' => 96, 'end' => 101, 'text' => 'Bully: Did she have curly hair or straight hair?'],
        ['start' => 101, 'end' => 104, 'text' => 'Friend: She had straight hair.'],
        ['start' => 104, 'end' => 108, 'text' => 'Bully: What color eyes did she have?'],
        ['start' => 108, 'end' => 111, 'text' => 'Friend: She had blue eyes.'],
        ['start' => 111, 'end' => 115, 'text' => 'Bully: Was she tall or short?'],
        ['start' => 115, 'end' => 118, 'text' => 'Friend: She was short.'],
        ['start' => 118, 'end' => 121, 'text' => 'Bully: Is this her?'],
        ['start' => 121, 'end' => 124, 'text' => "Friend: Yes, that's her."],
        ['start' => 124, 'end' => 129, 'text' => 'Bully: Hi everyone. Hello. Hi. Wow. Nice picture. Is that me?'],
        ['start' => 129, 'end' => 134, 'text' => "Bully: I don't know. Is it? Someone took Bully's birthday cake. Oh no."],
        ['start' => 134, 'end' => 142, 'text' => "Bully: But wait, this person can't be me."],
        ['start' => 142, 'end' => 151, 'text' => 'Bully: This person is tall and he has short blond curly hair and brown eyes.'],
        ['start' => 151, 'end' => 160, 'text' => "Bully: I'm tall and I have short blond curly hair, but I don't have brown eyes."],
        ['start' => 160, 'end' => 166, 'text' => 'Bully: I have blue eyes. Let us check again.'],
        ['start' => 166, 'end' => 175, 'text' => 'Friend: She had long brown straight hair and blue eyes.'],
        ['start' => 175, 'end' => 180, 'text' => 'Bully: She was short, right?'],
        ['start' => 180, 'end' => 183, 'text' => 'Friend: Yes, she was short.'],
        ['start' => 183, 'end' => 190, 'text' => 'Bully: Great. Thank you. Now I know who took the cake.'],
        ['start' => 190, 'end' => 196, 'text' => 'Friend: Do you want to find her now?'],
        ['start' => 196, 'end' => 202, 'text' => "Bully: Yes, let's go and find her."],
        ['start' => 202, 'end' => 209, 'text' => 'Narrator: Watch and repeat the appearance words: short, long, curly, straight, blond, brown, blue eyes.'],
        ['start' => 209, 'end' => 217, 'text' => 'Narrator: End of clip.'],
    ],

    'transcript' => [],
];
?>

@include('slider.video.interactive', ['content' => $content])
