<?php
$content = [
    'page_title' => '',
    'title' => 'Practice 2',
    'subtitle' => 'Watch again and do the quiz',

    'video' => materialAsset('slider/A2/Beginner/chapter-7/video/birthday-cake-encrypted/birthday-cake.m3u8'),
    'thumbnail' => materialAsset('slider/A2/Beginner/chapter-7/img/slide7.webp'),


    'isQuiz' => 0,

    'questions' => [
        [
            'time' => 28200,
            'type' => 'multiple_choice',
            'question' => '1) What hair colour did the man have?',
            'options' => [
                'Black',
                'Blonde',
                'Brown',
                'Red',
            ],
            'correct_answer' => 1,
            'points' => 10,
        ],
        [
            'time' => 33200,
            'type' => 'multiple_choice',
            'question' => '2) What kind of hair did the man have?',
            'options' => [
                'Long and straight',
                'Short and curly',
                'Long and curly',
                'Short and straight',
            ],
            'correct_answer' => 1,
            'points' => 10,
        ],
        [
            'time' => 72200,
            'type' => 'multiple_choice',
            'question' => '3) Why is the man not Arther?',
            'options' => [
                'He is short',
                'He has black hair',
                'He has brown eyes',
                'He has long hair',
            ],
            'correct_answer' => 2,
            'points' => 10,
        ],
        [
            'time' => 73100,
            'type' => 'true_false',
            'question' => '4) Arther has brown eyes.',
            'correct_answer' => false,
            'points' => 10,
        ],
        [
            'time' => 99200,
            'type' => 'true_false',
            'question' => '5) The woman had long brown straight hair.',
            'correct_answer' => true,
            'points' => 10,
        ],
    ],

    'subtitles' => [
        ['start' => 0, 'end' => 1.5, 'text' => "Arther: It's my birthday today."],
        ['start' => 2, 'end' => 3.5, 'text' => 'Friend: Happy birthday, Arther.'],
        ['start' => 3.7, 'end' => 4.7, 'text' => 'Arther: Thank you.'],
        ['start' => 5, 'end' => 9, 'text' => 'Friend: But Arther, do you have a birthday cake?'],
        ['start' => 9.7, 'end' => 14, 'text' => "Arther: Yes, it's right here. Where's my birthday cake?"],
        ['start' => 14.5, 'end' => 16, 'text' => 'Friend: I saw someone with your cake.'],
        ['start' => 16.8, 'end' => 19, 'text' => 'Arther: Was it a man or a woman?'],
        ['start' => 20.5, 'end' => 22, 'text' => 'Friend: It was a man.'],
        ['start' => 22, 'end' => 24, 'text' => 'Arther: A man? What did he look like?'],
        ['start' => 24.7, 'end' => 27, 'text' => 'Friend: He had short hair, blonde hair'],
        ['start' => 27, 'end' => 28, 'text' => 'Arther: Blonde hair.'],
        ['start' => 28.7, 'end' => 30.5, 'text' => 'Arther: Did he have curly hair or straight hair?'],
        ['start' => 31, 'end' => 33, 'text' => 'Friend: He had curly hair, brown eyes'],
        ['start' => 33.5, 'end' => 35, 'text' => 'Arther: Curly hair, brown eyes okay'],
        ['start' => 35.5, 'end' => 37, 'text' => 'Arther: Was he tall or short?'],
        ['start' => 37.5, 'end' => 39, 'text' => 'Friend: He was tall.'],
        ['start' => 39, 'end' => 42, 'text' => 'Arther: He was tall, Is this him?'],
        ['start' => 42, 'end' => 43.5, 'text' => "Friend: Yes, that's him."],
        ['start' => 45, 'end' => 46.5, 'text' => 'Hello everyone.'],
        ['start' => 46.5, 'end' => 48.3, 'text' => 'Hello. Hi.'],
        ['start' => 48.7, 'end' => 51, 'text' => 'Wow. Nice picture. Is that me?'],
        ['start' => 51, 'end' => 55.5, 'text' => "Arther: I don't know. Is it?"],
        ['start' => 55.8, 'end' => 58.3, 'text' => "Friend: Someone took Arther's birthday cake."],
        ['start' => 58.8, 'end' => 62, 'text' => "Oh no. But wait, this person can't be me."],
        ['start' => 62.7, 'end' => 67, 'text' => 'This person is tall and he has short blond curly hair and brown eyes.'],
        ['start' => 67, 'end' => 71, 'text' => "I'm tall and I have short blond curly hair, but I don't have brown eyes."],
        ['start' => 71, 'end' => 72, 'text' => 'I have blue eyes.'],
        ['start' => 73.7, 'end' => 76, 'text' => 'I saw someone with a cake, though.'],
        ['start' => 76, 'end' => 78.5, 'text' => 'Was it a man or a woman?'],
        ['start' => 79, 'end' => 81.5, 'text' => 'Friend: It was a woman.'],
        ['start' => 81.5, 'end' => 83.8, 'text' => 'Arther:A woman, What did she look like?'],
        ['start' => 84, 'end' => 85.5, 'text' => 'Friend: She had long hair.'],
        ['start' => 87.5, 'end' => 89.5, 'text' => 'Arther: What color hair did she have?'],
        ['start' => 89.5, 'end' => 92, 'text' => 'Friend: She had brown hair.'],
        ['start' => 92.5, 'end' => 95, 'text' => 'Arther: Did she have curly hair or straight hair?'],
        ['start' => 95, 'end' => 99, 'text' => 'She had straight hair. Long brown straight hair.'],
        ['start' => 99.5, 'end' => 100.5, 'text' => 'Arther: What color eyes did she have?'],
        ['start' => 101, 'end' => 102, 'text' => 'She had blue eyes.'],
        ['start' => 102, 'end' => 105, 'text' => 'Arther: Blue eyes, Was she tall or short?'],
        ['start' => 105.5, 'end' => 106.5, 'text' => 'She was short.'],
        ['start' => 111, 'end' => 113, 'text' => 'Arther: Is this her?'],
        ['start' => 113, 'end' => 114.5, 'text' => "Yes, that's her."],

    ],
    'transcript' => [],
];
?>

@include('slider.video.interactive', ['content' => $content])