@php
    $content = [
        'title'    => 'New Vocabulary',
        'subtitle' => '',

        'groups' => [
            [
                'key'        => 'with-images',
                'grid_class' => 'grid-cols-2 sm:grid-cols-4 lg:grid-cols-5',
                'items' => [
                    [
                        'text'     => 'biodiversity',
                        'subtitle' => 'the variety of plants, animals, and other living things in an area.',
                        'example'  => '',
                        'emoji'    => '',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-6/audios/slide5/biodiversity.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-6/img/slide5/biodiversity.webp'),
                    ],
                    [
                        'text'     => 'damage',
                        'subtitle' => 'harm or injury caused to something.',
                        'example'  => '',
                        'emoji'    => '',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-6/audios/slide5/damage.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-6/img/slide5/damage.webp'),
                    ],
                    [
                        'text'     => 'deforestation',
                        'subtitle' => 'the cutting down of trees in large areas.',
                        'example'  => '',
                        'emoji'    => '',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-6/audios/slide5/deforestation.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-6/img/slide5/deforestation.webp'),
                    ],
                    [
                        'text'     => 'pollution',
                        'subtitle' => 'the presence of harmful substances in the environment.',
                        'example'  => '',
                        'emoji'    => '',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-6/audios/slide5/pollution.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-6/img/slide5/pollution.webp'),
                    ],
                    [
                        'text'     => 'conserve energy',
                        'subtitle' => 'to use less energy in order to save resources and protect the planet.',
                        'example'  => '',
                        'emoji'    => '',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-6/audios/slide5/conserve-energy.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-6/img/slide5/conserve-energy.webp'),
                    ],
                    [
                        'text'     => 'carbon emission',
                        'subtitle' => 'the release of carbon dioxide and other gases into the air.',
                        'example'  => '',
                        'emoji'    => '',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-6/audios/slide5/carbon-emission.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-6/img/slide5/carbon-emission.webp'),
                    ],
                    [
                        'text'     => 'solar power',
                        'subtitle' => 'energy from the sun that can be used to produce power.',
                        'example'  => '',
                        'emoji'    => '',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-6/audios/slide5/solar-power.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-6/img/slide5/solar-power.webp'),
                    ],
                    [
                        'text'     => 'wind power',
                        'subtitle' => 'energy produced by the movement of wind.',
                        'example'  => '',
                        'emoji'    => '',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-6/audios/slide5/wind-power.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-6/img/slide5/wind-power.webp'),
                    ],
                    [
                        'text'     => 'absorb',
                        'subtitle' => 'to take in or soak up something, such as gas or liquid.',
                        'example'  => '',
                        'emoji'    => '',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-6/audios/slide5/absorb.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-6/img/slide5/absorb.webp'),
                    ],
                    [
                        'text'     => 'wildlife',
                        'subtitle' => 'animals living in their natural environment.',
                        'example'  => '',
                        'emoji'    => '',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-6/audios/slide5/wildlife.mp3'),
                        'image'    => materialAsset('slider/B1/Advanced/chapter-6/img/slide5/wildlife.webp'),
                    ],
                ],
            ],
            [
                'key'        => '',
                'grid_class' => 'grid-cols-2 sm:grid-cols-4 xl:grid-cols-5',
                'items' => [
                    [
                        'text'     => 'facing',
                        'subtitle' => 'experiencing or dealing with a problem or situation.',
                        'example'  => '',
                        'emoji'    => '🌍',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-6/audios/slide5/facing.mp3'),
                    ],
                    [
                        'text'     => 'major',
                        'subtitle' => 'very important or serious.',
                        'example'  => '',
                        'emoji'    => '❗',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-6/audios/slide5/major.mp3'),
                    ],
                    [
                        'text'     => 'require',
                        'subtitle' => 'to need something or make something necessary.',
                        'example'  => '',
                        'emoji'    => '📋',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-6/audios/slide5/require.mp3'),
                    ],
                    [
                        'text'     => 'affect',
                        'subtitle' => 'to have an effect on someone or something.',
                        'example'  => '',
                        'emoji'    => '💓',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-6/audios/slide5/affect.mp3'),
                    ],
                    [
                        'text'     => 'individuals',
                        'subtitle' => 'single people, as opposed to groups.',
                        'example'  => '',
                        'emoji'    => '🧍',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-6/audios/slide5/individuals.mp3'),
                    ],
                    [
                        'text'     => 'governments',
                        'subtitle' => 'the groups of people who have the power to make and enforce laws.',
                        'example'  => '',
                        'emoji'    => '🏛️',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-6/audios/slide5/governments.mp3'),
                    ],
                    [
                        'text'     => 'raise awareness',
                        'subtitle' => 'to inform people about an issue in order to encourage action.',
                        'example'  => '',
                        'emoji'    => '📢',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-6/audios/slide5/raise-awareness.mp3'),
                    ],
                    [
                        'text'     => 'collective action',
                        'subtitle' => 'people working together to achieve a common goal.',
                        'example'  => '',
                        'emoji'    => '🤝',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-6/audios/slide5/collective-action.mp3'),
                    ],
                    [
                        'text'     => 'organizations',
                        'subtitle' => 'groups of people working together for a common purpose.',
                        'example'  => '',
                        'emoji'    => '🔗',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-6/audios/slide5/organizations.mp3'),
                    ],
                    [
                        'text'     => 'reliance',
                        'subtitle' => 'the state of depending on or needing something.',
                        'example'  => '',
                        'emoji'    => '🌿',
                        'sound'    => materialAsset('slider/B1/Advanced/chapter-6/audios/slide5/reliance.mp3'),
                    ],
                ],
            ],
        ],
    ];
@endphp

@include('slider.vocab.image-card', ['content' => $content])